"""Core dataclasses and schema helpers shared across apps, workers, and evaluation."""

from .core import (
    AnnotationBundle,
    AuditEvent,
    BallInteraction,
    BoundingBox,
    ClipBoundaryRule,
    ClipCandidate,
    ClipRequest,
    Detection,
    DetectorFrameOutput,
    EvaluationMetricSpec,
    ExportJob,
    FrameReference,
    IdentityState,
    PossessionSegment,
    ProjectConfig,
    SelectionMode,
    TargetPlayerSelection,
    TrackObservation,
    TrackerFrameOutput,
    VideoAsset,
    WorkerCapability,
)

__all__ = [
    "AnnotationBundle",
    "AuditEvent",
    "BallInteraction",
    "BoundingBox",
    "ClipBoundaryRule",
    "ClipCandidate",
    "ClipRequest",
    "Detection",
    "DetectorFrameOutput",
    "EvaluationMetricSpec",
    "ExportJob",
    "FrameReference",
    "IdentityState",
    "PossessionSegment",
    "ProjectConfig",
    "SelectionMode",
    "TargetPlayerSelection",
    "TrackObservation",
    "TrackerFrameOutput",
    "VideoAsset",
    "WorkerCapability",
]
